### ISSUE TITLE
Old logs are not recorded during 9:00 PM and 11:59 PM

### ISSUE THREAD

**Issue by METZY1337** [BadgerCode/tttdamagelogs#50]
Between 9:00 PM and 11:59 PM, old logs of rounds that took place at these times are not recorded or are lost.

_In the video below, I show what happens if the first logs of the day are made during 11:00 PM._
https://streamable.com/5svgra

Update: The old logs from these specific times went into the next day old logs.
https://i.imgur.com/lKLUcpz.png

**Comment by BadgerCode** [comment]
Hey! Thanks for reporting this.

This is a strange bug.
Has this happened before?

**Comment by MetzyGG** [comment]
> Hey! Thanks for reporting this.
> 
> This is a strange bug.
> Has this happened before?

Yes, this issue has been happening for a few weeks now on my dedicated server, I also tested it on a local server and the issue happens too.
I am using SQLite, but I did a test using MySQL and the issue still happens.

**Comment by BadgerCode** [comment]
Hm that's annoying.

I will need to reproduce this using my local Garry's Mod so that I can debug the issue further.

**Comment by wgaylord** [comment]
I can confirm this happens with 3.4.3. Beening trying to wrap my head around why for sometimes our oldlogs are broken and at other times it works properly.

**Comment by wgaylord** [comment]
Looking thru the oldlog code some more I think this is partially due to the UTC time usage in the database. 

All the os.date calls are not prefixed with `!` https://wiki.facepunch.com/gmod/os.date so they are returning the year,month and day in local time but the date in the database is saved as a unix epoch with is in UTC time. So when when the logs are selected they show a UTC day. 

Log selection https://github.com/BadgerCode/tttdamagelogs/blob/master/lua/damagelogs/server/oldlogs.lua#L237

But when the year, month and days are selected its using local time. 

Year https://github.com/BadgerCode/tttdamagelogs/blob/master/lua/damagelogs/server/oldlogs.lua#L137
Month https://github.com/BadgerCode/tttdamagelogs/blob/master/lua/damagelogs/server/oldlogs.lua#L144
Day https://github.com/BadgerCode/tttdamagelogs/blob/master/lua/damagelogs/server/oldlogs.lua#L151
