### ISSUE TITLE
Issue: Discombobulator not showing as DMG in log

### ISSUE THREAD

**Issue by michael-harman** [BadgerCode/tttdamagelogs#54]
The disco doesn't show kills or dmg in the log.  Just has shot logs for it.

**Comment by BadgerCode** [comment]
Hey.

The discombobulater should count as a kill or count as the damage source if the person it pushes dies/takes damage within 4 seconds of it pushing them.
I copied this logic from the TTT gamemode, since otherwise it becomes a bit difficult working out if the fall damage is from the discombobulater or not.

https://www.github.com/BadgerCode/tttdamagelogs/tree/master/lua%2Fdamagelogs%2Fserver%2Finit.lua
Line 102 - GetPlayerThatRecentlyPushedMe


It's used in the fall damage event.

https://github.com/BadgerCode/tttdamagelogs/blob/master/lua/damagelogs/shared/events/fall_damage.lua


Is it possible that the players taking the damage have fallen for more than 4 seconds?

**Comment by michael-harman** [comment]
I figured it out.  Up in the top right one, the fall damage filter somehow was turned off, seemingly by default because none of my admins could see it either.  Sorry to waste your time on this one haha.

**Comment by BadgerCode** [comment]
Ah no worries.
Easy solution 😛

Possibly we might want to change the default behaviour of that filter so that fall damage is shown by default
