### ISSUE TITLE
Strange Lua Error with Discord Webhook for report updating

### ISSUE THREAD

**Issue by razorzinho** [BadgerCode/tttdamagelogs#92]
Some rare times when receiving report updates, the field "responseMessage" might get broken and be sent as a boolean value for a gsub() function.

The error is as follows:

```
[tttdamagelogs] addons/tttdamagelogs/lua/damagelogs/server/discord.lua:79: attempt to index field 'responseMessage' (a boolean value)
  1. DiscordMessage - addons/tttdamagelogs/lua/damagelogs/server/discord.lua:79
   2. func - addons/tttdamagelogs/lua/damagelogs/server/rdm_manager.lua:839
    3. unknown - lua/includes/extensions/net.lua:38
```

```
if discordUpdate.responseMessage ~= nil then
        local forgivenRow = {
            name = TTTLogTranslate(nil, "ReportedPlayerResponse") .. ":",
            value = discordUpdate.responseMessage:gsub("([%*_~<>\\@[])", "\\%1")
        }
        table.insert(data.fields, forgivenRow)
end
```

As you can see, in the code snippet above, the function only checks if the value for `responseMessage` is nil. Which should be ok, but, after checking the rest of the file `rdm_manager.lua`, that field is also assigned as false to begin with. So, in some rare occasions, that could be left unchanged, and be sent as false, which won't be ruled out by that `~= nil` condition, since boolean and nil are different things, causing an error.

I have a proposition for solution which involves changing the file rdm_manager.lua and updating that assignment logic. Any other ideas or suggestions for it?

**Comment by BadgerCode** [comment]
Heyo!

Looking at the current code, discordUpdate.responseMessage is always either a string or nil.

https://github.com/BadgerCode/tttdamagelogs/blob/3c463d2b358e33b32a82e2ccc26ad3ba596e1c14/lua/damagelogs/server/rdm_manager.lua#L380-L397

https://github.com/BadgerCode/tttdamagelogs/blob/3c463d2b358e33b32a82e2ccc26ad3ba596e1c14/lua/damagelogs/server/rdm_manager.lua#L566-L592

https://github.com/BadgerCode/tttdamagelogs/blob/3c463d2b358e33b32a82e2ccc26ad3ba596e1c14/lua/damagelogs/server/rdm_manager.lua#L628-L654

https://github.com/BadgerCode/tttdamagelogs/blob/3c463d2b358e33b32a82e2ccc26ad3ba596e1c14/lua/damagelogs/server/rdm_manager.lua#L820-L839

**Comment by BadgerCode** [comment]
Have you made any changes to the code?

**Comment by BadgerCode** [comment]
The code `tbl.response or "Unknown"` will evaluate to a string, and default to "Unknown" if there's no response

```lua
local tbl = { }

print(tbl.response or "Unknown")
-- Prints unknown


local tbl2 = {
   response = "hello"
}

print(tbl2.response or "Unknown")
-- Prints hello
```

**Comment by r47orr** [comment]
Hello! Thanks for the response!

> Have you made any changes to the code?
About this, I don't recall changing anything except for the settings. If I am not mistaking, I am using version 3.6.2

> https://github.com/BadgerCode/tttdamagelogs/blob/3c463d2b358e33b32a82e2ccc26ad3ba596e1c14/lua/damagelogs/server/rdm_manager.lua#L566-L592
> 
> https://github.com/BadgerCode/tttdamagelogs/blob/3c463d2b358e33b32a82e2ccc26ad3ba596e1c14/lua/damagelogs/server/rdm_manager.lua#L628-L654
> 
> https://github.com/BadgerCode/tttdamagelogs/blob/3c463d2b358e33b32a82e2ccc26ad3ba596e1c14/lua/damagelogs/server/rdm_manager.lua#L820-L839
About this part, specifically the last code snippet, as you can see on line 833, the field `responseMessage` has no callback, which I suspect being the cause of the error, since, as you can see, in the other two previous ones, there is a callback value to guarantee a string value.

Couldn't this be a mistake or are you sure that value is completely safe without a callback? 

Also, couldn't this be a mistake and, in some rare occasions, the value for response not be altered to nil or a string? Could be a "bug" when a reported player leave or something like that and that false doesn't change, so it would bypass the 
`if responseMessage ~= nil then` 

> https://github.com/BadgerCode/tttdamagelogs/blob/3c463d2b358e33b32a82e2ccc26ad3ba596e1c14/lua/damagelogs/server/rdm_manager.lua#L360-L375

So, in that case, I'd either change the default value of `response` to `nil` or add another callback value to the last `responseMessage` update occurrency

**Comment by BadgerCode** [comment]
Heyo!

Sorry for the delay.
Did you manage to find out any more about this issue?
