### ISSUE TITLE
Failing to create Report Panel

### ISSUE THREAD

**Issue by marcandreher** [BadgerCode/tttdamagelogs#96]
`[tttdamagelogs-master] lua/includes/extensions/client/panel/scriptedpanels.lua:30: bad argument #2 to 'Create' (Panel expected, got function)
  1. Create - [C]:-1
   2. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:30
    3. AddReport - addons/tttdamagelogs-master/lua/damagelogs/client/rdm_manager.lua:93
     4. BuildReportFrame - addons/tttdamagelogs-master/lua/damagelogs/client/rdm_manager.lua:175
      5. func - addons/tttdamagelogs-master/lua/damagelogs/client/rdm_manager.lua:848
       6. unknown - lua/includes/extensions/net.lua:38
`
Usage: TTT2
Model doesn't open when answering reports

**Comment by BadgerCode** [comment]
Heyo!
What version of the damagelogs are you using?

The version is in the top-bar when you open the damage logs

**Comment by BadgerCode** [comment]
Looking at the error, it's in some code that hasn't changed for 2 years.
So it might be related to a GMod update.

`local MessageEntry = vgui.Create("DTextEntry", BuildReportFrame)`
BuildReportFrame is a function


https://wiki.facepunch.com/gmod/vgui.Create
The method doesn't take in a function, so this surely would have not worked for some time


This will require some investigation

**Comment by wgaylord** [comment]
This is because an update (still sort of in dev builds but the 64-bit beta has it) made some functions start checking argument types instead of ignoring the incorrect types.   I went back thru some versions on github and found that originally that function took self as the argument, then during a large update `BuildReportFrame` ended up there. My guess is it was supposed to be just `ReportFrame` but it also works properly if you just remove the argument since it gets assigned to the `ReportFrame` manually a bit lower down.

**Comment by marcandreher** [comment]
Version: 3.7.0

**Comment by BadgerCode** [comment]
This has been fixed in #98 and will be included in the next damage logs release

**Comment by BadgerCode** [comment]
This fix has been released here & on the workshop
https://github.com/BadgerCode/tttdamagelogs/releases/tag/v3.8.0
